package types

enum class PassportElementUnspecifiedType {
    PERSONAL_DETAILS, PASSPORT, DRIVER_LICENSE, IDENTITY_CARD, INTERNAL_PASSPORT, ADDRESS,
    UTILITY_BILL, BANK_STATEMENT, RENTAL_AGREEMENT, PASSPORT_REGISTRATION, TEMPORARY_REGISTRATION,
}